package:
  name: minicli
  version: 4.2.0
  epoch: 0
  description: "Minimalist CLI framework for PHP"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - php-8.2
      - wolfi-baselayout

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - php-8.2

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/minicli/minicli
      tag: ${{package.version}}
      expected-commit: 1675c0609205c106bb7c2353888dec361808d92e

  - name: Install minicli
    runs: |
      mkdir -p ${{targets.destdir}}/usr/share/php/minicli
      cp -r src/* ${{targets.destdir}}/usr/share/php/minicli/

subpackages:
  - name: ${{package.name}}-bin
    description: "Minicli CLI command"
    dependencies:
      runtime:
        - php-8.2
        - minicli
        - wolfi-baselayout
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          cat <<'EOF' > ${{targets.subpkgdir}}/usr/bin/minicli
          #!/bin/sh
          exec php /usr/share/php/minicli/minicli "$@"
          EOF
          chmod +x ${{targets.subpkgdir}}/usr/bin/minicli

update:
  enabled: false
  reason: "Fixed to version 4.2.0 for compatibility with existing applications"