package:
  name: nginx
  version: 1.26.0
  epoch: 0
  description: "High performance web server"
  copyright:
    - license: BSD-2-Clause
  dependencies:
    runtime:
      - openssl
      - pcre2
      - wolfi-baselayout
      - zlib

environment:
  contents:
    packages:
      - build-base
      - busybox
      - openssl-dev
      - pcre2-dev
      - zlib-dev
      - wget

pipeline:
  - uses: fetch
    with:
      uri: https://nginx.org/download/nginx-${{package.version}}.tar.gz
      expected-sha256: d2e6c8439d6c6db5015d8eaab2470ab52aef85a7bf363182879977e084370497 #31327d30a6ff81e5e4a1a442ad183859bc0d751d1e06a2e84dc7a1af416229

  - uses: autoconf/configure
    with:
      opts: |
        --prefix=/usr \
        --sbin-path=/usr/sbin/nginx \
        --conf-path=/etc/nginx/nginx.conf \
        --pid-path=/var/run/nginx.pid \
        --lock-path=/var/run/nginx.lock \
        --http-client-body-temp-path=/var/cache/nginx/client_temp \
        --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
        --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
        --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
        --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
        --user=nginx \
        --group=nginx \
        --with-threads \
        --with-http_ssl_module \
        --with-http_v2_module \
        --with-http_realip_module \
        --with-http_addition_module \
        --with-http_sub_module \
        --with-http_dav_module \
        --with-http_flv_module \
        --with-http_mp4_module \
        --with-http_gunzip_module \
        --with-http_gzip_static_module \
        --with-http_random_index_module \
        --with-http_secure_link_module \
        --with-http_stub_status_module \
        --with-http_auth_request_module \
        --with-mail \
        --with-mail_ssl_module \
        --with-stream \
        --with-stream_ssl_module \
        --with-stream_realip_module \
        --with-stream_ssl_preread_module

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  manual: false
  release-monitor:
    identifier: 11583  # Nginx trên release-monitoring.org

test:
  pipeline:
    - runs: |
        nginx -v
