package:
  name: php-8.2
  version: 8.2.28
  epoch: 0
  description: "the PHP programming language"
  copyright:
    - license: PHP-3.01
  dependencies:
    provides:
      - php=${{package.full-version}}
    runtime:
      - ${{package.name}}-config
      - libxml2
      - wolfi-baselayout
environment:
  contents:
    packages:
      - gcc
      - build-base
      - busybox
      - ca-certificates-bundle
      - libxml2-dev
      - oniguruma-dev
      - openssl-dev
      - sqlite-dev
      - zlib-dev
      - wget
      
pipeline:
  - uses: fetch
    with:
      uri: https://www.php.net/distributions/php-${{package.version}}.tar.gz
      expected-sha256: 3318300888de5023720cc84efad5e005e53f30b5f0072fae65a750dabcaf6ec3
      extract: false

  - name: Prepare Build Folder
    runs: |
      mv php-${{package.version}}.tar.gz $HOME
      tar zxf $HOME/php-${{package.version}}.tar.gz

  - name: Configure
    runs: |
      cd $HOME/php-${{package.version}}
      EXTENSION_DIR=/usr/lib/php/modules ./configure \
        --prefix=/usr \
        --libdir=/usr/lib/php \
        --sysconfdir=/etc/php \
        --with-config-file-path=/etc/php \
        --with-config-file-scan-dir=/etc/php/conf.d \
        --enable-cli \
        --with-openssl=shared \
        --with-zlib \
        --enable-mbstring=shared \
        --with-libxml \
        --enable-fpm

  - uses: autoconf/make
    with:
      dir: $HOME/php-${{package.version}}

  - name: Make Install
    runs: |
      cd $HOME/php-${{package.version}}
      INSTALL_ROOT=${{targets.destdir}} DESTDIR=${{targets.destdir}} make install

  - uses: strip

subpackages:
  - name: ${{package.name}}-config
    dependencies:
      provides:
        - php-config=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          mv $HOME/php-${{package.version}}/php.ini-production ${{targets.subpkgdir}}/etc/php/php.ini

  - name: ${{package.name}}-fpm
    description: PHP 8.2 FastCGI Process Manager (FPM)
    dependencies:
      runtime:
        - ${{package.name}}-fpm-config
        - wolfi-baselayout
      provides:
        - php-fpm=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/sbin"
          mv ${{targets.destdir}}/usr/sbin/php-fpm ${{targets.subpkgdir}}/usr/sbin/

  - name: ${{package.name}}-fpm-config
    description: PHP 8.2 FPM configuration
    dependencies:
      provides:
        - php-fpm-config=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/etc/php/php-fpm.d
          mv ${{targets.destdir}}/etc/php/php-fpm.conf.default ${{targets.subpkgdir}}/etc/php/php-fpm.conf
          mv ${{targets.destdir}}/etc/php/php-fpm.d/www.conf.default ${{targets.subpkgdir}}/etc/php/php-fpm.d/www.conf
          echo '[global]\nerror_log = /proc/self/fd/2\ndaemonize = no\n[www]\nlisten = [::]:9000' > ${{targets.subpkgdir}}/etc/php/php-fpm.d/zz-apko.conf

update:
  enabled: true
  github:
    identifier: php/php-src
    strip-prefix: php-
    tag-filter: php-8.2
    use-tag: true

test:
  pipeline:
    - runs: |
        php --version
        php /tmp/hello.php <<<'<?php echo "Hello, Wolfi!";'
