FROM cgr.dev/chainguard/wolfi-base:latest

RUN echo "https://wolfi.duyne.me" >> /etc/apk/repositories && \
cat <<EOF > /etc/apk/keys/melange.rsa.pub
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA1kuqmxeTo+oBBp9kolVx
IFuHULV3G+wglqvGgctGxlN6Q6YNOW0+KyT+Z0UF/+U/9qUDH6l8DXroQS/w0emv
lIk5Xv03nMTcrJ9Jo6ljqthI3Y9Ku13GnV6nCoCfUW/UZzgWeoUu4C3gRGEqHLHz
vtIY18iTJg312WjN0t85V0OGkMevzuKFCCY4ngnhysInlB9/N1MfWSyAnc2wC8rj
XZocAh/IRxsu96fIPhljL2ggFQezJUn3onDC1rrJIOCSUm0vcerB636jRTdukRvX
NJXe7V4GxbAyOSlekXKmYlCIkqRpEmKkRf4H+jCMFoSrHAPbU1IA7TkLR2q6uMD2
f6de8qTO8oEINCrRKpjMMMY7uyg3H+57rkSwPBSrz7di1ZlvOSypUwm/fYcyt3lF
BFsvBH/Th8QlYHQVsYQ/K4Mwtcl1h7SmwzABiOhmGLLQmGUS2rj0Sk/e5KfZ0gt4
1fg3mvVkTl40mQdMNFBXvqe0w/PXjkAlK6epoDtBpSS/Sx7mmUvKxVU9/572lGK3
enkRZDywTZuh2kS//8uG0zGNUXWSy2xftG3Kw369aneZ41ZesQhG0xKmyW/2Of1S
vXDEjEeob9dYZjlbs5RVKrjSPX4mwh4LMj7HsdkBHVZ8d2nuVekq8vbbRgkcSa5e
tbmdukAIJyoKLCSGREe0VnUCAwEAAQ==
-----END PUBLIC KEY-----
EOF
