FROM cgr.dev/chainguard/wolfi-base:latest

RUN echo "https://wolfi.duyne.me" > /etc/apk/repositories && \
    echo "https://packages.wolfi.dev/os" >> /etc/apk/repositories && \
    cat <<EOF > /etc/apk/keys/melange.rsa.pub
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxXIZH2F27lZ0QI3cMJXk
DX+JYBCe91zmHJ4BxQPvTCGWopES024+a+jPnCEaRA5ZPFxJC0i1jwcFOnSvW33Z
Gua2g0uUo4DYrPZEapL181YrxqLaDqGiUXqVOmVaXfMFeBcPhWMN84D8quYEhZy1
5Qe101Ers2XfqHU0fSbkbHxaC19XkHJi1xFtHJ+Bt7c2Dunmxtwd10dT0FGQbQSC
PGNdpM9WaKRgjiPqwa6ypLjixrKZGgQkBQr8wpjCJl5wgEhYLY2HnKtxP+wuvKGy
H2iljOSDOd/jFk9Iq0qzSM/LC43oUDl29L/gytJr1WRFAwD+WZ5MNmlUiWToO/n4
axoz070mdy326cGKD+WnEXG5DiE7QvWtnryswqvYkYM6MPFszgo+R11llhHWU+6A
Zp+mukrUCd/2yK6jFyUGSvGkJzc+g4lbGhSKTQgS662pKaW8Evw+TyezcySOZSbu
pnAqt5XxMy0AR4r7JRMRzaKJnksY2LUC039V2Wl8JJKKLrdjYWge0VXvC3WDch6V
mPoyvsSz7jd0Nn/bihYt+ot6eMS4nE3fAFDIUeUujuxP3tECHC87YFAt10N4wRPk
2HeKjRAHZYdAXaAwzNn5XOV89Rb08HqiqOqR5tbhgVnmPlnlv+gk41gnG9rukdOo
9WkUoFfXdpDPBJGi/XD9kjsCAwEAAQ==
-----END PUBLIC KEY-----
EOF
