issuer: https://token.actions.githubusercontent.com
subject: repo:duyhenryer/wolfi:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: duyhenryer/wolfi/.github/workflows/wolfictl-update-gh.yaml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
  workflows: write
  issues: write
