issuer: https://token.actions.githubusercontent.com
subject: repo:shyim/wolfi-php:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: shyim/wolfi-php/.github/workflows/wolfictl-update-rm.yaml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
  workflows: write
  issues: write
