name: Wolfictl Update From GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: read
  id-token: write

env:
  GIT_AUTHOR_NAME: frosh-ci
  GIT_AUTHOR_EMAIL: ci@fos.gg

jobs:
  update:
    name: Wolfictl Update
    if: github.repository == 'duyhenryer/wolfi'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      # Step 2: Use the Octo-Sts Action to generate a token
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: github-updates

      # Step 3: Run the reusable workflow
      - name: Run Wolfictl Update
        uses: duyhenryer/workflows/.github/workflows/wolfictl-update-gh.yaml@wolfictl
        with:
          repository: ${{ github.repository }}
          token: ${{ steps.octo-sts.outputs.token }}  # Use the token from the octo-sts step
          git_author_name: ${{ env.GIT_AUTHOR_NAME }}
          git_author_email: ${{ env.GIT_AUTHOR_EMAIL }}
