name: Wolfictl Update From GitHub

on:
  workflow_dispatch:
  # Triggers the workflow every hour
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: read
  id-token: write

env:
  GIT_AUTHOR_NAME: frosh-ci
  GIT_AUTHOR_EMAIL: ci@fos.gg

jobs:
  update:
    name: Wolfictl Update
    if: github.repository == 'duyhenryer/wolfi'
    
    # Use the reusable workflow here
    uses: duyhenryer/workflows/.github/workflows/wolfictl-update-gh@wolfictl
    with:
      repository: ${{ github.repository }}
      token: ${{ secrets.GITHUB_TOKEN }}
      git_author_name: ${{ env.GIT_AUTHOR_NAME }}
      git_author_email: ${{ env.GIT_AUTHOR_EMAIL }}
